spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: username
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: parquimetro
  data:
    mongodb:
      uri: mongodb+srv://root:LEiLqeb5FzeqLR89@postechfiap.zqzyfmo.mongodb.net/?retryWrites=true&w=majority&appName=PosTechFiap
      database: PosTechFiap
server:
  servlet:
    contextPath: "/parkingmeter/api"

parquimetro:
  email-noreply: "noreply@parquimetro.com.br"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
